// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApp.Entities.Data;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(TestingFinalContext))]
    [Migration("20250514112221_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Entities.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Role1")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("role_pkey");

                    b.HasIndex(new[] { "Role1" }, "role_role_key")
                        .IsUnique();

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role1 = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Role1 = "User"
                        });
                });

            modelBuilder.Entity("WebApp.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Createdby")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("Createdtime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdtime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime>("Lastmodifiedtime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodifiedtime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Modifiedby")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("modifiedby");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("user_pkey");

                    b.HasIndex("Createdby");

                    b.HasIndex("Modifiedby");

                    b.HasIndex("RoleId");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Createdby = 1,
                            Createdtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4242),
                            Isdeleted = false,
                            Lastmodifiedtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4252),
                            Modifiedby = 1,
                            Password = "GYTHWp4fhH6h5hv/WFDkR9zOqaNkQq4I2paR3u9yflY=",
                            RoleId = 1,
                            Username = "dhruvsavsani1"
                        },
                        new
                        {
                            Id = 2,
                            Createdby = 1,
                            Createdtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4256),
                            Isdeleted = false,
                            Lastmodifiedtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4256),
                            Modifiedby = 1,
                            Password = "GYTHWp4fhH6h5hv/WFDkR9zOqaNkQq4I2paR3u9yflY=",
                            RoleId = 2,
                            Username = "dhruvsavsani2"
                        },
                        new
                        {
                            Id = 3,
                            Createdby = 1,
                            Createdtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4258),
                            Isdeleted = false,
                            Lastmodifiedtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4258),
                            Modifiedby = 1,
                            Password = "GYTHWp4fhH6h5hv/WFDkR9zOqaNkQq4I2paR3u9yflY=",
                            RoleId = 2,
                            Username = "dhruvsavsani3"
                        },
                        new
                        {
                            Id = 4,
                            Createdby = 1,
                            Createdtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4260),
                            Isdeleted = false,
                            Lastmodifiedtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4260),
                            Modifiedby = 1,
                            Password = "GYTHWp4fhH6h5hv/WFDkR9zOqaNkQq4I2paR3u9yflY=",
                            RoleId = 2,
                            Username = "dhruvsavsani4"
                        },
                        new
                        {
                            Id = 5,
                            Createdby = 1,
                            Createdtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4262),
                            Isdeleted = false,
                            Lastmodifiedtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4262),
                            Modifiedby = 1,
                            Password = "GYTHWp4fhH6h5hv/WFDkR9zOqaNkQq4I2paR3u9yflY=",
                            RoleId = 2,
                            Username = "dhruvsavsani5"
                        },
                        new
                        {
                            Id = 6,
                            Createdby = 1,
                            Createdtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4264),
                            Isdeleted = false,
                            Lastmodifiedtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4264),
                            Modifiedby = 1,
                            Password = "GYTHWp4fhH6h5hv/WFDkR9zOqaNkQq4I2paR3u9yflY=",
                            RoleId = 2,
                            Username = "dhruvsavsani6"
                        },
                        new
                        {
                            Id = 7,
                            Createdby = 1,
                            Createdtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4266),
                            Isdeleted = false,
                            Lastmodifiedtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4266),
                            Modifiedby = 1,
                            Password = "GYTHWp4fhH6h5hv/WFDkR9zOqaNkQq4I2paR3u9yflY=",
                            RoleId = 2,
                            Username = "dhruvsavsani7"
                        },
                        new
                        {
                            Id = 8,
                            Createdby = 1,
                            Createdtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4268),
                            Isdeleted = false,
                            Lastmodifiedtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4268),
                            Modifiedby = 1,
                            Password = "GYTHWp4fhH6h5hv/WFDkR9zOqaNkQq4I2paR3u9yflY=",
                            RoleId = 2,
                            Username = "dhruvsavsani8"
                        },
                        new
                        {
                            Id = 9,
                            Createdby = 1,
                            Createdtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4311),
                            Isdeleted = false,
                            Lastmodifiedtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4311),
                            Modifiedby = 1,
                            Password = "GYTHWp4fhH6h5hv/WFDkR9zOqaNkQq4I2paR3u9yflY=",
                            RoleId = 2,
                            Username = "dhruvsavsani9"
                        },
                        new
                        {
                            Id = 10,
                            Createdby = 1,
                            Createdtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4313),
                            Isdeleted = false,
                            Lastmodifiedtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4313),
                            Modifiedby = 1,
                            Password = "GYTHWp4fhH6h5hv/WFDkR9zOqaNkQq4I2paR3u9yflY=",
                            RoleId = 2,
                            Username = "dhruvsavsani10"
                        },
                        new
                        {
                            Id = 11,
                            Createdby = 1,
                            Createdtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4315),
                            Isdeleted = false,
                            Lastmodifiedtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4315),
                            Modifiedby = 1,
                            Password = "GYTHWp4fhH6h5hv/WFDkR9zOqaNkQq4I2paR3u9yflY=",
                            RoleId = 2,
                            Username = "dhruvsavsani11"
                        },
                        new
                        {
                            Id = 12,
                            Createdby = 1,
                            Createdtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4316),
                            Isdeleted = false,
                            Lastmodifiedtime = new DateTime(2025, 5, 14, 16, 52, 21, 386, DateTimeKind.Local).AddTicks(4317),
                            Modifiedby = 1,
                            Password = "GYTHWp4fhH6h5hv/WFDkR9zOqaNkQq4I2paR3u9yflY=",
                            RoleId = 2,
                            Username = "dhruvsavsani12"
                        });
                });

            modelBuilder.Entity("WebApp.Entities.Models.User", b =>
                {
                    b.HasOne("WebApp.Entities.Models.User", "CreatedbyNavigation")
                        .WithMany("InverseCreatedbyNavigation")
                        .HasForeignKey("Createdby")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_createdby");

                    b.HasOne("WebApp.Entities.Models.User", "ModifiedbyNavigation")
                        .WithMany("InverseModifiedbyNavigation")
                        .HasForeignKey("Modifiedby")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modifiedby");

                    b.HasOne("WebApp.Entities.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_id");

                    b.Navigation("CreatedbyNavigation");

                    b.Navigation("ModifiedbyNavigation");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApp.Entities.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApp.Entities.Models.User", b =>
                {
                    b.Navigation("InverseCreatedbyNavigation");

                    b.Navigation("InverseModifiedbyNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
